name: easycalc
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  dio: 3.0.7
  datetime_picker_formfield: 1.0.0-pre.5
  get_it: 3.0.3
  google_fonts: 0.2.0
  bloc: ^3.0.0
  flutter_bloc: ^3.1.0
  equatable: ^1.0.0

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  mockito: 4.1.1
  bloc_test: ^3.0.1

flutter:
  uses-material-design: true
